general:
  concurrent-entities: 3
hbase:
  root: /opt/cloudera/parcels/CDH/lib/hbase/conf
  hBase-site: ${hbase.root}/hbase-site.xml
  jaas-file: ${hbase.root}/jaas.conf
  krb5-file: /etc/krb5.conf
  key-tab: /appserver/kerberos_keytab/ooxp.keytab
  hBase-nameSpace: ooxpqa
  hbase-instances-table: ooxpqa:instances
  hadoop-user: bigdata-app-ooxpqa-service@INTQA.THOMSONREUTERS.COM
  bin-dir: ${user.dir}
es:
  hostname: qa-ooxp-trtra-es.int.thomsonreuters.com
  port: 443
  protocol: https
  username: ooxp-qa-rw
  password: aujnKT6kiP8sUCPB5Ssmfw==
  prefix: ooxp-qa
  shards: 1
  replicas: 1
  retries: 10
  reindex-suffix: runid
  default-batch-size: 1000
  mappings-dir: mappings/
  cluster-name: qa-es-trta-ooxp
  reporting-index: ooxp-qa-rebuild-status