general:
  concurrency: 3
  app-name: ooxp-data-migration
hadoop:
  root: /opt/cloudera/parcels/CDH/lib/hbase/conf
  hBase-site: ${hbase.root}/hbase-site.xml
  jaas-file: ${hbase.root}/jaas.conf
  krb5-file: /etc/krb5.conf
  key-tab: /appserver/kerberos_keytab/ooxp.keytab
  hBase-nameSpace: ooxpdev
  hbase-instances-table: ooxpdev:instances
  hadoop-user: bigdata-app-ooxpdev-service@INTQA.THOMSONREUTERS.COM
  bin-dir: ${user.dir}
