general:
  concurrent-entities: 3
hbase:
  root: /opt/cloudera/parcels/CDH/lib/hbase/conf
  hBase-site: ${hbase.root}/hbase-site.xml
  jaas-file: ${hbase.root}/jaas.conf
  krb5-file: /etc/krb5.conf
  key-tab: /appserver/kerberos_keytab/ooxp.keytab
  hBase-nameSpace: ooxpdev
  hbase-instances-table: ooxpdev:instances
  hadoop-user: bigdata-app-ooxpdev-service@INTQA.THOMSONREUTERS.COM
  bin-dir: ${user.dir}
es:
  hostname: dev-ooxp-trtra-es.int.thomsonreuters.com
  port: 80
  protocol: http
  username: ooxp-dev-readwrite
  password: wsAveLuLcJgeqTxcsYIFFw==
  prefix: ooxp-dev
  shards: 1
  replicas: 1
  retries: 10
  reindex-suffix: runid
  default-batch-size: 1000
  mappings-dir: mappings/
  cluster-name: es-trta-ooxp-eag
  reporting-index: ooxp-dev-rebuild-status